# 语言
language: java

# Java版本
jdk:
  - openjdk11

# 跳过安装
install: true

# 编译命令
script: mvn clean package -P release -D skipTests=true -D gpg.skip=true -D maven.source.skip=true -D maven.javadoc.skip=true
